import type { PluginProject, PluginVersion, ServerTarget } from '@salvadiux/shared';

const headers = {'User-Agent':'SalvadiuxHost/0.1.0 (https://github.com/salvadiux/host)',Accept:'application/json'};
async function json<T>(url:string):Promise<T>{const response=await fetch(url,{headers,signal:AbortSignal.timeout(15_000)});if(!response.ok)throw new Error(`Provider returned ${response.status}`);return response.json() as Promise<T>}
export interface PluginProvider{id:string;name:string;search(query:string,target:ServerTarget):Promise<PluginProject[]>;getVersions(projectId:string,target:ServerTarget):Promise<PluginVersion[]>}

export class ModrinthProvider implements PluginProvider{
 id='modrinth';name='Modrinth';
 async search(query:string,target:ServerTarget):Promise<PluginProject[]>{const facets=JSON.stringify([[`versions:${target.minecraftVersion}`],['project_type:plugin']]);const data=await json<{hits:any[]}>(`https://api.modrinth.com/v2/search?query=${encodeURIComponent(query)}&facets=${encodeURIComponent(facets)}&limit=20`);return data.hits.map(x=>({id:x.project_id,provider:this.id,name:x.title,slug:x.slug,description:x.description,iconUrl:x.icon_url,authors:[x.author],downloads:x.downloads,updatedAt:x.date_modified,sourceUrl:`https://modrinth.com/plugin/${x.slug}`}))}
 async getVersions(projectId:string,target:ServerTarget):Promise<PluginVersion[]>{const loaders=target.software==='vanilla'?[]:target.software==='velocity'?['velocity']:['paper','purpur','spigot','bukkit'];const data=await json<any[]>(`https://api.modrinth.com/v2/project/${encodeURIComponent(projectId)}/version?game_versions=${encodeURIComponent(JSON.stringify([target.minecraftVersion]))}`);return data.filter(v=>!loaders.length||v.loaders.some((x:string)=>loaders.includes(x))).flatMap(v=>{const file=v.files.find((x:any)=>x.primary)??v.files[0];if(!file)return[];return[{id:v.id,projectId,provider:this.id,name:v.name,versionNumber:v.version_number,gameVersions:v.game_versions,platforms:v.loaders,releaseType:v.version_type,fileName:file.filename,fileUrl:file.url,dependencies:(v.dependencies??[]).filter((x:any)=>x.dependency_type==='required'&&x.project_id).map((x:any)=>({projectId:x.project_id,required:true})),hashes:file.hashes}]})}
}
export class HangarProvider implements PluginProvider{
 id='hangar';name='Hangar';
 async search(query:string,_target:ServerTarget):Promise<PluginProject[]>{const data=await json<{result:any[]}>(`https://hangar.papermc.io/api/v1/projects?q=${encodeURIComponent(query)}&limit=20`);return(data.result??[]).map(x=>({id:x.namespace?.slug??x.name,provider:this.id,name:x.name,description:x.description,iconUrl:x.avatarUrl,authors:x.owner?[x.owner]:undefined,sourceUrl:`https://hangar.papermc.io/${x.namespace?.owner}/${x.namespace?.slug}`}))}
 async getVersions(projectId:string,target:ServerTarget):Promise<PluginVersion[]>{const data=await json<{result:any[]}>(`https://hangar.papermc.io/api/v1/projects/${encodeURIComponent(projectId)}/versions?limit=50`);const platform=target.software==='velocity'?'VELOCITY':'PAPER';return(data.result??[]).filter(v=>(v.platformDependencies?.[platform]??[]).includes(target.minecraftVersion)).flatMap(v=>{const file=v.downloads?.[platform];if(!file)return[];return[{id:v.name,projectId,provider:this.id,name:v.name,versionNumber:v.name,gameVersions:v.platformDependencies[platform],platforms:[platform.toLowerCase()],releaseType:v.channel?.name?.toLowerCase()==='release'?'release':'unknown',fileName:`${projectId}-${v.name}.jar`,fileUrl:file.downloadUrl,dependencies:[],hashes:file.externalUrl?undefined:{}}]})}
}
export const providerRegistry=new Map<string,PluginProvider>([['hangar',new HangarProvider()],['modrinth',new ModrinthProvider()]]);
export function compatible(version:PluginVersion,target:ServerTarget):boolean{const platforms=target.software==='purpur'?['purpur','paper','spigot','bukkit']:target.software==='velocity'?['velocity']:[target.software,'spigot','bukkit'];return version.gameVersions.includes(target.minecraftVersion)&&version.platforms.some(p=>platforms.includes(p))}
